#!/bin/bash

# Set decoration geometry
berryc title_height       30
berryc inner_border_width 8
berryc border_width       4
berryc edge_gap           0 0 0 0

# Set decoration colors
berryc inner_focus_color   #c9cba3
berryc focus_color         #472d30
berryc text_focus_color    #ffffff

berryc inner_unfocus_color #565679
berryc unfocus_color       #292D3E
berryc text_unfocus_color  #eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Dina-9"